Fix javadoc build issue:
[ERROR] /tmp/w712/apache-wicket-7.12.0/wicket-core/src/main/java/org/apache/wicket/page/PartialPageUpdate.java:307: error - JavaScript found in documentation comment.
[ERROR] Use --allow-script-in-comments to allow use of JavaScript.

(cherry picked from commit bcf516a3928f7db8af87f046de12450bafe74a7f)